name: 'SonarQube Scanner-Linux'
author: 'Jim Seiwert'
description: 'Scans your code using the sonarqube batch file'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  host-url:  # id of input
    description: 'URL to SonarQube'
    required: true
  token:  # id of input
    description: 'SonarQube token'
    required: true
  project-key:  # id of input
    description: 'The name of the SonarQube project'
    required: true
  project-name:  # id of input
    description: 'The name of the SonarQube project'
    required: true
  sq-version:  # id of input
    description: 'The version of the SonarQube scanner'
    required: true   
    default: "4.6.1.2450"      

runs:
  using: "composite"
  steps:
    - name:  Install the required packages
      run:  |
        mkdir /downloads/sonarqube -p
        cd /downloads/sonarqube\
        echo https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ inputs.sq-version }}-linux.zip
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ inputs.sq-version }}-linux.zip
        unzip sonar-scanner-cli-${{ inputs.sq-version }}-linux.zip
        mv sonar-scanner-${{ inputs.sq-version }}-linux /opt/sonar-scanner
      shell: bash 

    - name:  Install
      run:  /opt/sonar-scanner --define sonar.host.url="${{ inputs.host-url }}" --define sonar.login="${{ inputs.token }}" --define sonar.projectKey="${{  inputs.project-key }}" --define sonar.projectName="${{ inputs.project-name }}"
      shell: bash